pipeline:
  name: dr-apps
  identifier: drapps
  projectIdentifier: ai_application_engine
  orgIdentifier: No_Code_Apps
  tags: {}
  stages:
    - stage:
        name: Setup
        identifier: Setup
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup Environment
                  identifier: Setup_Environment
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: python:3.9
                    shell: Sh
                    command: |-
                      set -ex
                      make req-test
                    resources:
                      limits:
                        memory: 8Gi
                        cpu: "4"
    - parallel:
        - stage:
            name: Lint
            identifier: Lint
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              execution:
                steps:
                  - step:
                      type: Run
                      name: Lint
                      identifier: Run_Lint
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.9
                        shell: Sh
                        command: |-
                          set -ex
                          make lint
                        resources:
                          limits:
                            memory: 8Gi
                            cpu: "4"
        - stage:
            name: Unit Test
            identifier: Unit_Test
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run Unit Tests
                      identifier: Tests
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.9
                        shell: Sh
                        command: |-
                          set -ex
                          make test
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /harness/results.xml
                        resources:
                          limits:
                            memory: 2Gi
                            cpu: "1"
    - stage:
        name: AllExpectedTasks
        identifier: AllExpectedTasks
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            useFromStage: Lint
          execution:
            steps:
              - step:
                  type: Run
                  name: AllExpectedTasks
                  identifier: AllExpectedTasks
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: node:20.11.1
                    shell: Sh
                    command: exit 0
        when:
          pipelineStatus: Success
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: dr-apps
        build: <+input>
